name: billboard - Post Tweet

on:
  schedule:
    # Runs at 0 minutes past the hour, every 8 hours (3 Tweets/Day). 
    - cron: "0 */8 * * *"
  workflow_dispatch:
jobs:
  post_tweet:
    name: Post daily tweet
    runs-on: ubuntu-latest
    steps:
      - uses: potternate/twitterbot@main
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
